### ISSUE TITLE
app defaults, yes please :)

### ISSUE THREAD

**Issue by typemytype** [justvanrossum/fontgoggles#83] opened 2020-04-06 09:20 UTC
https://github.com/justvanrossum/fontgoggles/blob/e30e5cf6614422a1eb01e4ff82146b0c32afef3a/Lib/fontgoggles/project.py#L194

maybe it FG could save the last entry to the defaults, used for new documents.

**Comment by justvanrossum** [comment] 2020-04-06 09:34
Duplicate of #40

**Closed by justvanrossum** 2020-04-06 09:34 UTC
