### ISSUE TITLE
Feature request: view font name table data

### ISSUE THREAD

**Issue by arrowtype** [justvanrossum/fontgoggles#32] opened 2020-02-22 22:34 UTC
This is probably a bigger request than I realize, especially because so many font formats are accepted here. So, feel free to disregard/close this if you don't think it's within the intended purview of the tool. But...

Many times a day, I want to pop open a font and see its name table. Of course, I can use `ttx -t name <font>` and open the result in a code editor, but it would be pretty amazing to be able to just drag-and-drop a font or two onto the FontGoggles icon and see the data instantly.

There are other tools for this, but FontTableViewer refuses to open variable fonts, and OTMaster is just less nice than FontGoggles.

Still, it might be that table viewing is well outside the spec for this app, and that totally makes sense. Just wanted to suggest that someday in the future, it may be a nice layer of functionality to add.

**Comment by justvanrossum** [comment] 2020-02-23 06:10
Yes, I'm afraid that this is out of scope for FontGoggles, at least at this time.

By design, it's not a "discovery" app: for example it also doesn't give you the option to see which characters a font defines.

Btw., just in case you didn't know already: for ad hoc inspection, the `-o -` ttx option is super handy, as it will send the output to the terminal instead of writing it to a file.

**Closed by justvanrossum** 2020-02-23 06:10 UTC

**Comment by arrowtype** [comment] 2020-02-23 15:16
Totally understandable. Yeah, it already does a lot, and I have no clue where table info would fit in.

> for ad hoc inspection, the -o - ttx option is super handy, as it will send the output to the terminal instead of writing it to a file.

Ahh thank you! I thought I might get a good tip like this. :)

I also ended up setting up a function in my `.bash_profile` so that I can see name tables with nicer XML syntax highlighting than my terminal gives.

```
name () {
  ttx -t name $1
  code ${1/.*tf/.ttx}
  open "$(dirname "$1")"
}
```
